In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/diabetes.csv')

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.tail()


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [5]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
df.shape

(768, 9)

In [7]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [10]:
X = df.drop('Outcome',axis=1)
Y = df['Outcome']

In [11]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [12]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

In [16]:
x_train.shape

(576, 8)

In [17]:
x_test.shape

(192, 8)

In [19]:
from sklearn.preprocessing import StandardScaler
c = StandardScaler()
x_train=c.fit_transform(x_train)
x_train

array([[ 1.50755225, -1.01521454, -0.40451932, ..., -1.22070104,
        -0.98325882, -0.04863985],
       [-0.82986389, -0.09964691, -0.61509602, ...,  0.13719053,
        -0.62493647, -0.88246592],
       [-1.12204091, -0.95207195,  0.54307587, ...,  0.0240329 ,
         0.39884168, -0.5489355 ],
       ...,
       [ 0.04666716, -0.85735805, -0.24658679, ..., -0.9440935 ,
        -0.96519215, -1.04923114],
       [ 2.09190629, -1.14149973,  0.2272108 , ..., -0.26514771,
        -0.5075031 ,  0.11812536],
       [ 0.33884418,  0.46863645,  0.64836422, ..., -4.04964181,
         0.51627505,  2.953134  ]])

In [20]:
x_test=c.fit_transform(x_test)
x_test

array([[-0.89466499,  2.40832035,  0.42614323, ...,  1.5176708 ,
         2.78154275, -0.93394179],
       [-0.58177669, -0.40019425,  0.32738704, ...,  0.29631107,
        -0.23748131, -0.84250027],
       [ 0.04399992, -1.34654156, -0.26515007, ...,  0.34884267,
        -0.27712506, -0.65961722],
       ...,
       [-0.89466499, -0.33913959, -0.36390625, ..., -0.78058677,
         1.41840764, -1.02538331],
       [-0.26888838,  0.24087973,  0.52489941, ..., -1.34530148,
        -0.65221593,  2.08362842],
       [ 0.35688822, -0.98021357,  0.52489941, ..., -0.49166296,
        -0.68271112,  0.43768103]])

In [21]:
import tensorflow as tf
from tensorflow import keras

In [44]:
model = keras.Sequential([
                              keras.layers.Flatten(input_shape=(8,)),
                              keras.layers.Dense(20,activation='relu'),
                              keras.layers.Dense(3,activation = 'sigmoid')
])

In [45]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [47]:
history = model.fit(x_train,y_train,validation_split=0.1,epochs=10)

Epoch 1/10
17/17 [==============================] - 0s 9ms/step - loss: 0.8885 - accuracy: 0.6737 - val_loss: 0.8731 - val_accuracy: 0.7586
Epoch 2/10
17/17 [==============================] - 0s 5ms/step - loss: 0.8316 - accuracy: 0.7085 - val_loss: 0.8192 - val_accuracy: 0.8103
Epoch 3/10
17/17 [==============================] - 0s 4ms/step - loss: 0.7816 - accuracy: 0.7181 - val_loss: 0.7732 - val_accuracy: 0.7931
Epoch 4/10
17/17 [==============================] - 0s 4ms/step - loss: 0.7384 - accuracy: 0.7259 - val_loss: 0.7332 - val_accuracy: 0.7931
Epoch 5/10
17/17 [==============================] - 0s 5ms/step - loss: 0.7008 - accuracy: 0.7375 - val_loss: 0.7004 - val_accuracy: 0.7586
Epoch 6/10
17/17 [==============================] - 0s 4ms/step - loss: 0.6693 - accuracy: 0.7432 - val_loss: 0.6726 - val_accuracy: 0.7759
Epoch 7/10
17/17 [==============================] - 0s 4ms/step - loss: 0.6423 - accuracy: 0.7510 - val_loss: 0.6500 - val_accuracy: 0.7931
Epoch 8/10
17/17 [==

In [48]:
y_pred = model.predict(x_test)

6/6 [==============================] - 0s 2ms/step


In [49]:
y_pred

array([[0.79429513, 0.85040146, 0.29498187],
       [0.79282504, 0.5339593 , 0.40345576],
       [0.7446522 , 0.26396146, 0.24394824],
       [0.5902912 , 0.74091935, 0.24185322],
       [0.7118523 , 0.3913117 , 0.3593023 ],
       [0.79566205, 0.26358312, 0.34232646],
       [0.61751115, 0.86824346, 0.25561872],
       [0.48746175, 0.8021701 , 0.23852512],
       [0.91470605, 0.648522  , 0.40040028],
       [0.7874728 , 0.76607233, 0.16897462],
       [0.69265884, 0.7732563 , 0.3208269 ],
       [0.42784646, 0.8652921 , 0.08763576],
       [0.7462153 , 0.68797594, 0.41612107],
       [0.9291671 , 0.5274214 , 0.2704463 ],
       [0.8541603 , 0.6914567 , 0.30495816],
       [0.6864915 , 0.5012914 , 0.374335  ],
       [0.52819747, 0.89215845, 0.11660286],
       [0.85554725, 0.2152536 , 0.27559116],
       [0.66737604, 0.7688174 , 0.2153628 ],
       [0.73349255, 0.6205455 , 0.31920627],
       [0.6072768 , 0.7268587 , 0.21737601],
       [0.6869108 , 0.4621131 , 0.43022662],
       [0.

In [50]:
y_pred = np.argmax(y_pred,axis=1)

In [51]:
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0])

In [52]:
from sklearn.metrics import accuracy_score , confusion_matrix
a=accuracy_score(y_test,y_pred)
a

0.796875

In [53]:
c=confusion_matrix(y_test,y_pred)
c

array([[113,  17],
       [ 22,  40]])